######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 30 02:54:32 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += my-tools.h nfq-manager.h protocols.h \
    flow-manager.h
SOURCES += main.cpp my-tools.cpp protocols.cpp
LIBS += -lnetfilter_queue
